### ISSUE TITLE
UI issue in enabler - button size

### ISSUE THREAD

**Issue by vkanishk** [openxc/openxc-ios-app-demo#42]
![simulator screen shot - iphone 8 plus - 2018-01-10 at 12 26 39](https://user-images.githubusercontent.com/20083167/34761509-23ddf34e-f60a-11e7-87f4-2042b76375c5.png)
![simulator screen shot - iphone 8 plus - 2018-01-10 at 12 27 25](https://user-images.githubusercontent.com/20083167/34761510-243c0808-f60a-11e7-80b5-979d49ea81d6.png)
![simulator screen shot - iphone x - 2018-01-10 at 12 29 07](https://user-images.githubusercontent.com/20083167/34761511-2486e44a-f60a-11e7-9260-bf302bf862b2.png)
![simulator screen shot - iphone x - 2018-01-10 at 12 29 20](https://user-images.githubusercontent.com/20083167/34761512-24e3dd76-f60a-11e7-8a8e-4c82ae31630e.png)

**Comment by kranjanford** [comment]
Fixed this issue in Ui_Changes branch
